apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: docagent
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - redis.yaml
  - api.yaml
  - worker.yaml
  - hpa.yaml
