apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: ConfigMap
      name: docagent-config
    patch: |-
      - op: replace
        path: /data/DOCAGENT_PROVIDER
        value: fake
  - target:
      kind: Deployment
      name: api|worker
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            memory: 2Gi
